upstream active_backend {
    server api-green:3000;
}

upstream standby_backend {
    server api-green:3000;
}

server {
    listen 80;

    location / {
        proxy_pass http://active_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /test-standby/ {
        proxy_pass http://standby_backend/;
        proxy_set_header Host $host;
    }
}